analytics-id: 
#Pages
pages:
  - {name: 'Episodes', link: 'https://feeds.buzzsprout.com/1815426.rss'}

social:
  - {icon: 'twitter', type: "brand", link: 'https://twitter.com/k_feuilleton'}
  - {icon: 'facebook', type: "brand", link: 'https://www.facebook.com/kdramafeuilleton/'}  
  - {icon: 'envelope', type: "solid", link: 'mailto:kdramafeuilleton@gmail.com'}
  - {icon: 'rss', type: "solid", link: "https://feeds.buzzsprout.com/1815426.rss"}

websites-podcast:
  - {name: 'Apple Podcast', link: 'https://podcasts.apple.com/us/podcast/k-drama-feuilleton/id1575721396'}
  - {name: 'Spotify', link: 'https://open.spotify.com/show/18rQ1ySFRQNYdlrq5vercc'}
  - {name: 'Audible', link: 'https://www.audible.com/pd/Podcast/B08K57XRKR'}
  - {name: 'stitcher', link: 'https://www.stitcher.com/show/kdrama-feuilleton'}
  - {name: 'RSS', link: 'https://feeds.buzzsprout.com/1815426.rss'}

translate-date: true #See _includes/date.html to translate the months' name
shownotes: true

#Disqus
disqus:
  disqus_shortname: 
